# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: graphgenerator
version: '0.0.0'
github: "Tarmean/graphgenerator"
license: MIT
author: "Cyril Fahlenbock"
maintainer: "Cyril Fahlenbock"
# synopsis: A new Haskeleton package.
# description: graphgenerator is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - gloss
  - fgl
  - mtl
  - containers
  - logict
  - lens
  - primitive

  - tasty
  - tasty-hspec
  source-dirs: library

executables:
  prog:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - graphgenerator
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  graphgenerator-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - graphgenerator
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  graphgenerator-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - graphgenerator
    - tasty
    - tasty-hspec
    - fgl
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
